[package]
name = "kobalt-widgets"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Official widget library for Kobalt UI framework"

[dependencies]
kobalt-core = { version = "0.0.2", path = "../kobalt-core" }

[dev-dependencies]
